name: Hello Github Actions

on:
  push:
    branches:
      - main
    paths:
      - 'basic-actions/**'

jobs:
  hello:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: basic-actions

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Display Message
        run: echo "Hello from Github Actions!"

      - name: Run Python
        run: python3 hello.py