name: Flask Employee Management CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          cd Employee-Management
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check Python Version
        run: python --version

      - name: List Project Files
        run: ls -la

      - name: Run Flask Application Check
        run: |
          cd Employee-Management
          python app.py



# C:\Users\DELL\Desktop\Github_Actions\Employee-Management\.github\workflows\ci.yml