name: Flask Employee Management CI

on:
  push:
    branches:
      - main
    paths:
      - 'Employee-Management/**'

  pull_request:
    branches:
      - main
    paths:
      - 'Employee-Management/**'

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: Root@123
          MYSQL_DATABASE: employee_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -pRoot@123"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    defaults:
      run:
        working-directory: Employee-Management

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install MySQL Client
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client

      - name: Create Employees Table
        run: |
          mysql -h 127.0.0.1 -uroot -pRoot@123 employee_db < schema.sql

      - name: Check Python Version
        run: python --version

      - name: Run Pytest
        run: python -m pytest -v